### ISSUE TITLE
Test IMU

### ISSUE THREAD

**Issue by ffund** [ZidongGuo/Desktop-Roomba#11]
Gyro Accelerometer IMU: Connect SCL, GND, SDA, and Vin on the IMU and check if Pi can reach the part with SPI communication. In addition, test to see if the IMU returns correct values.

- [x]  Connect the IMU to power and see if it is on
- [x]  Connect the I2C bus and verify that it is visible on the bus
- [x] Add IMU setup to `Setup_IMU` function in Desktop Roomba library and make sure it works
- [x] Add code to `Read_Angle` and `Read_Acceleration` and make sure it works
- [x] Collect measurements while moving the IMU in a way similar to how the robot will move. Make sure it can reflect a positive or negative 90 degree and 180-degree turn as well as moving left/right/forward/backward

**Comment by ffund** [comment]
### Connect IMU to power

Connect the VIN and GND pins on the IMU to 3.3V and GND on the Pi. Verify that the LED on the breakout board turns on.

Expected result: LED on board turns on.
![image](https://user-images.githubusercontent.com/61918160/112746450-6f245e00-8fe1-11eb-980f-1cc582549788.png)

**Comment by ffund** [comment]
### Connect I2C bus

Connect the SCL and SDA pins to I2C SDA and SCL on the Pi (GPIO2 and GPIO3). 

Run 

```
i2cdetect -y 1
```

and make sure the IMU appears at expected address.

Expected result: should see a device at 0x6A.
![image](https://user-images.githubusercontent.com/61918160/112746685-1950b580-8fe3-11eb-9b21-1c95484f2524.png)

**Comment by ZidongGuo** [comment]
### Implement IMU_Setup(), Read_Acceleration() and Read_Angle()
![image](https://user-images.githubusercontent.com/61918160/113865240-7405c080-97de-11eb-866f-6a90e4764023.png)
