### ISSUE TITLE
Remove auto-generated files from Python install from tracking, and add a .gitignore

### ISSUE THREAD

**Issue by ffund** [ZidongGuo/Desktop-Roomba#18]
The files that are automatically generated by `sudo python3 setup.py install` shouldn't be tracked in Git - they will cause merge conflict unnecessarily, and we don't need to track them because we don't change them manually.

You should remove them from tracking (with `git rm`) and then add a `.gitignore` so that Git commands won't even show them to you from now on.

More explanation: https://realpython.com/lessons/gitignore-file/

A good `.gitignore` for Python: https://github.com/github/gitignore/blob/master/Python.gitignore

**Comment by ZidongGuo** [comment]
### Remove folders including DesktopRoomba.egg-info, Desktop_Roomba.egg-info, __pycache__, build/lib and dist with git rm
![image](https://user-images.githubusercontent.com/61918160/114716946-256c9f00-9d67-11eb-8227-4b5f6ca89286.png)


### Add .gitignore
